[Feat] 좋아요 구현 (프론트)
Kernel360/E2E2-LOOK-US pull request #114
Opened 2024-08-16 05:22 UTC by limbaba1120

예전에 백엔드에서 작성한 좋아요 기능을 프론트로 구현했습니다.

2024-08-16 05:25 UTC, Minju-Kimm commented on backend/src/main/java/org/example/post/controller/PostPublicController.java
> +	@GetMapping("/{postId}/like-status")
likeStatus 추가 좋아요

2024-08-16 05:28 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/controller/PostPublicController.java
> +	@GetMapping("/{postId}/like-status")
이 부분은 추후에 PostPreview와 PostDetail에서 body에 포함시켜서 보내주는 게 맞습니다.

2024-08-16 05:30 UTC, Minju-Kimm reviewed
전체 코드 확인했습니다. 수정 사항 반영해주시면 approve 할게요!!

2024-08-16 05:30 UTC, Minju-Kimm commented on backend/src/main/java/org/example/post/controller/PostPublicController.java
> +	@GetMapping("/{postId}/like-status")
`PostApiController`로 이동해주셔야 할 것 같습니다

2024-08-16 05:30 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/service/PostService.java
> +	public UserEntity findUserByEmail(String email) {
USER_DEACTIVATE가 아니라 USER_NOT_FOUND로 되어야 합니다.

2024-08-16 05:31 UTC, tigris24 submitted a review, later dismissed
수정사항 확인했습니다

2024-08-16 05:31 UTC, kimminkyeu requested changes, later dismissed
코멘트 남긴 부분 확인해주시고 변경되면 태그 부탁드립니다!

2024-08-17 04:26 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/controller/PostPublicController.java
> +	@GetMapping("/{postId}/like-status")
네 일단 다음에 코드 전체 고칠 때 수정하겠습니다.

2024-08-17 04:33 UTC, limbaba1120 commented
> @limbaba1120 코멘트 남긴 부분 확인해주시고 변경되면 태그 부탁드립니다!

@kimminkyeu  likestatus 빼고 수정했습니다!

2024-08-17 07:53 UTC, kimminkyeu submitted a review, later dismissed

2024-08-17 08:10 UTC, tigris24 submitted a review, later dismissed
확인하였습니다 고생하셨습니다

2024-08-17 10:04 UTC, Minju-Kimm submitted a review, later dismissed
수고 많으셨어요~!!!

2024-08-17 13:42 UTC, tigris24 approved these changes, later dismissed

2024-08-17 13:53 UTC, Minju-Kimm commented on backend/src/main/java/org/example/post/domain/dto/PostDto.java
> +		public static PostDetailDtoResponse toDto(PostEntity postEntity, boolean likeStatus) {
+ 스크랩부분도 팔로우부분도 넣을 수 있으면 좋을 것 같습니다(월요일에 같이 이야기 나눠봐요.)

2024-08-17 13:57 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/domain/dto/PostDto.java
> +		public static PostDetailDtoResponse toDto(PostEntity postEntity, boolean likeStatus) {
넵!!

2024-08-18 06:27 UTC, Minju-Kimm approved these changes, later dismissed
comment 남긴 것들 확인해주시면 감사하겠습니다. 수고 많으셨어요 :)

2024-08-18 06:27 UTC, Minju-Kimm commented on backend/src/main/java/org/example/post/domain/dto/PostDto.java
> +				likeStatus,
likeStatus와 로그인된 사용자 간의 검증로직이 있는지 궁금합니다.

2024-08-18 06:27 UTC, Minju-Kimm commented on frontend/src/app/_api/post.ts
> +export async function likePost(postId: number) {
좋아요는 이렇게 하면 DB에 반영될 것으로 확인 되는데, 포스트 상세조회 부분에서 이슈가 발생한다 판단됩니다. 포스트 상세조회시 로그인/비로그인 사용자 검증로직이 추가되어야 할 것 같습니다.

2024-08-18 06:45 UTC, merged