[Feat] 해시태그와 기존 검색어로 게시글 검색 관련 기능 추가 및 수정
Kernel360/E2E2-LOOK-US pull request #48
Opened 2024-08-03 13:59 UTC by tigris24

#40 
- HashtagEntity, HashtagRepository 추가
- PostApiController getAllPosts 에서 RequestParam으로 searchHashtags List 타입으로 변경
- PostService 에서 검색어, 해시태그 만으로 조회 가능하도록 변경 및 둘다 없을때 전체 조회로 수정
- 둘 다 검색어로 주어지는 경우는 검색어와 해시태그를 모두 가진 게시물만 조회
- Entity 에서 Post 1:N Hashtag 로 매핑
- PostEntity에 getHashtagContents 추가 : List -> List
- HashtagEntity 에 생성자 추가 -> hashtagRepository 사용하기 위해
- 해시태그 관련 Post DTO 모두 수정

2024-08-03 14:02 UTC, tigris24 commented
PostResponseDto 에 hashtagContets 가 추가되었으나 매퍼 관련은 전체적인 리팩토링 이슈에 수정될 예정이라 변경해두지는 않았습니다.

2024-08-04 00:37 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/controller/PostApiController.java
>  	@GetMapping("/posts")
위에는 /api/v1/posts인데 여기는 /posts로 되어있습니다.

2024-08-04 00:42 UTC, tigris24 commented on backend/src/main/java/org/example/post/controller/PostApiController.java
>  	@GetMapping("/posts")
맞춰서 수정해두었습니다.

2024-08-04 00:43 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/domain/entity/HashtagEntity.java
> +@RequiredArgsConstructor(access = AccessLevel.PROTECTED)
여기에 왜 @RequiredArgsConstructor가 필요한가요? PostEntity에도 있던데...

아마 @NoArgsConstructor이랑 헷갈린것 같슴니다

2024-08-04 00:46 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/domain/entity/PostEntity.java
> +	@OneToMany(mappedBy = "postEntity", fetch = FetchType.LAZY)
mappedBy="post" 아래에 mapping 한것과 다릅니다.

2024-08-04 00:52 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/service/PostService.java
>  	public ResponseEntity<PaginationResponseDto> getAllPostsOrderedBySortStrategy(
이번에 멘토링을 통해 이 코드를 더 효율적으로 개선할 수 있을지 물어봅시당. 저도 계속 고민하고 생각하고 있는데 도저히 제 머리속에서 해답이 안나오네요..

2024-08-04 02:26 UTC, kimminkyeu requested changes
고생하셨습니다...!
코드 리뷰 코멘트 남겼으니 검토 부탁드립니다!

2024-08-04 02:26 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/domain/entity/PostEntity.java
>  	private List<UserPostLikesEntity> likesList;
## 1. 생성자 내 likeCount의 필요성
PostEntity 생성자에선 likeCount를 넣지 않는게 좋다고 생각됩니다.

그렇다면 setLikeCount를 따로 명시해줘야 할텐데, 
setLikeCount 메소드의 필요성도 의문이 듭니다. 

저는 incrementLikes 메소드를 통해 `좋아요 1개`만 증가되도록 하는 것이 안전하다고 생각됩니다.
```suggestion
    // JPA에서 해당 함수가 호출될 때, 알아서 persist 해주는지 좀 더 찾아보겠습니다...!
	public void incrementLikes() {
        this.likes += 1;
    }

    post.incrementLikes(); // --> 알아서 jpa가 좋아요 증가를 persist 하는지는 확인 필요
```
이런 경우 `setLikeCount`를 금지하기 위해, `@setter`는 안쓰는게 좋겠네요.

### 참고 자료
- https://okky.kr/questions/903921


## 2. 추후 고민할 문제: 좋아요 동시성 처리
이건 좋아요 처리 방법을 찾아보다가 발견한 스택오버플로우 글입니다.
좋아요 요청이 동시에 여러개 발생할 때, 동시성 처리를 어떻게 하는지에 대한 질문입니다. 

### 참고 자료
- https://stackoverflow.com/questions/30143594/spring-jpa-and-hibernate-how-to-increment-a-counter-without-concurrency-issu

좋아요 동시성 처리는 저희팀이 분명 추후에 고민하게 될 것 같아요~
일단 링크만 남깁니다.

2024-08-04 02:26 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/service/PostService.java
## 추후 변경 필요 
### (지금은 변경 안하셔도 됩니다. 추후 메모용 코멘트입니다.)

postDto는 ImageFile이 들어옵니다. (BlobFile)
반면, postEntity는 image_id가 들어갑니다.

따라서 이 부분은 ImageStorageManager를 사용하면서 아래와 같이 변경될 예정입니다.

```suggestion

// 1. 이미지를 스토리지에 저장
Long savedImageId = imageStorageManger.saveImageFile( postDto.getImageFile() );

// 2. 포스트 엔티티 생성
PostEntity postEntity = new PostEntity(
			user,
			postDto.getPostContent(),
			savedImageId
			PostStatus.PUBLISHED // Set default status
		);

```

2024-08-04 02:45 UTC, tigris24 reviewed
리뷰 요청 수정 사항

2024-08-04 03:07 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/dto/request/PostRequestDto.java
>  	@JsonProperty("post_content")
일단은 ERD 가 변경되지 않아서 requestDto 에서는 변경해두었고, createPost에서는 toString으로 억지로 형태만 맞춰둔 상태입니다.

2024-08-04 03:47 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/entity/HashtagEntity.java
> +	@ManyToOne(fetch = FetchType.LAZY)
단방향으로 수정되었습니다.

2024-08-04 04:15 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/dto/request/PostRequestDto.java
> +	public PostRequestDto(String userId, String imageSrc, String postContent) {
제가 조회쪽만 하다보니 수정이 안되었었네요 추가했습니다.

2024-08-04 04:16 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/entity/UserPostLikesEntity.java
>  	@ManyToOne(fetch = FetchType.LAZY)
일단 cascade 추가해두었습니다.

2024-08-04 04:16 UTC, tigris24 commented on backend/src/main/java/org/example/post/repository/PostRepository.java
> +	Page<PostEntity> findAllByPostContentContainingAndPostStatus(
해시태그를 이용한 join이 들어가다보니 쿼리문을 작성하게 되었습니다.

2024-08-04 04:17 UTC, tigris24 commented on backend/src/main/java/org/example/post/repository/PostRepository.java
> +	Page<PostEntity> findAllByHashtagsContainingAndPostStatus(
같은 이유로 쿼리문을 이용해 해시태그 내용을 이용한 조회를 하기 위함입니다.

2024-08-04 04:19 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/entity/PostEntity.java
일단 추후에 다같이 확인해보면 좋을 것 같습니다.

2024-08-04 04:20 UTC, tigris24 commented on backend/src/main/java/org/example/post/domain/entity/PostEntity.java
>  	private List<UserPostLikesEntity> likesList;
likeslist에 대한 것이면 초반에 만들어져있었는데 아직 좋아요와 관련된 부분은 건들지 않고 있는 상태이다보니 로직에도 포함되는 부분은 없어서 굳이 수정하지 않았습니다만 말씀하신대로 고민해볼 사항이라고 저도 생각합니다.

2024-08-04 04:22 UTC, tigris24 commented on backend/src/main/java/org/example/post/service/PostService.java
일단은 이미지 타입에 맞춰 엔티티 생성시에도 추가되도록 설정해두었으나 정확한 요청 보내는 방식을 찾지 못하여 정확한 동작에 대한 검증은 못하였습니다. 
이미지 추가와 관련된 pr 추가되면 확인해야합니다.

2024-08-04 04:23 UTC, tigris24 reviewed
추가적인 pr에 대한 업데이트입니다.

2024-08-04 04:26 UTC, tigris24 commented on backend/src/main/java/org/example/post/controller/PostApiController.java
>  	@GetMapping("/posts")
현재 /api 로 들어가는 포스트맨 요청이 401으로 처리되는 시큐리티 권한 관련 이슈가 있어서 /posts 로 변경해두었습니다.

2024-08-04 04:30 UTC, limbaba1120 commented on backend/src/main/java/org/example/post/controller/PostApiController.java
>  	@GetMapping("/posts")
post man 에서 전송할 때 accesstoken이 없어서 이슈가 발생했을 겁니다!

2024-08-04 04:34 UTC, limbaba1120 approved these changes
고생하셨습니다. 수정한거 확인했습니다!

2024-08-04 05:02 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/domain/entity/UserPostLikesEntity.java
>  	@ManyToOne(fetch = FetchType.LAZY)
토의해보고 결정할 사항이니 메모용으로 댓글 남깁니다.
- 좋아요에 대한 cascacade / nullable 검토 예정

2024-08-04 05:04 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/repository/PostRepository.java
> +	Page<PostEntity> findAllByPostContentContainingAndPostStatus(
만약 jpa 기능을 써서 join 쿼리를 생성할 수 있다면, 직접 쿼리를 명시하는 것보다 나은 것 같습니다. 월요일에 검토해보고 결정해봐요.

2024-08-04 05:06 UTC, kimminkyeu commented on backend/src/main/java/org/example/post/service/PostService.java
네 알겠습니다!

2024-08-04 05:06 UTC, kimminkyeu approved these changes

2024-08-04 05:07 UTC, kimminkyeu approved these changes
변경 사항 모두 확인하였습니다.
리뷰 댓글은 월요일에 더 이야기해보시죠.
고생 하셨습니다!

2024-08-04 05:10 UTC, kimminkyeu commented
@tigris24 리뷰 마치겠습니다. 편하실 때 머지 해주시면 됩니다! :+1:

2024-08-04 05:30 UTC, merged